name: i4think
favicon: null
layout_spectrum: 0.25059
typography_spectrum: 0.75319
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5777035914361477
  lightness: 0.9334380587097257
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
